site_name: LinkedIn

theme: 
  name: material
  favicon: assets/linkedin-logo.png
  logo: assets/linkedin-logo.png
  language: 'pt'
  palette:
    primary: 'indigo'
nav:
  - Página Inicial: index.md
  - Planejamento do Projeto:
    - Cronograma de Atividades: ./planejamento/cronograma.md
    - Análise dos aplicativos:  ./planejamento/analise-app.md
    - Plano de Metodologias:    ./planejamento/metodologias.md
    - Ferramentas utilizadas:   ./planejamento/ferramentas.md
  - Pré-Rastreabilidade:
    - Rich Picture: ./preRastreabilidade/richPicture.md
  - Elicitação:
    - Personas: ./elicitacao/personas.md
    - Técnicas:
      - Brainstorm: ./elicitacao/brainstorm.md
      - Observação: ./elicitacao/observacao.md
      - Entrevistas: ./elicitacao/entrevistas.md
      - Introspecção: ./elicitacao/introspeccao.md
      - Storytelling: ./elicitacao/storytelling.md
    - Priorização:
      - MoScoW: ./elicitacao/moscow.md
      - First Things First: ./elicitacao/first_things_first.md
  - Modelagem:
    - Cenários: ./modelagem/cenarios.md
    - Léxicos: ./modelagem/lexicos.md
    - Casos de Uso: ./modelagem/casos-de-uso.md
    - Especificação Suplementar: ./modelagem/especificacao-suplementar.md
  - Atas e Reuniões:
    - Novembro:
      - Dia 28 - Brainstorm: ./atas_e_reunioes/28-11-Brainstorm.md
      - Dia 28 - Entrevista: ./atas_e_reunioes/28-11-Entrevista.md
  - Apresentações: ./apresentacoes/apresentacoes.md
markdown_extensions:
- attr_list
