site_name: LinkedIn

theme: 
  name: material
  favicon: assets/linkedin-logo.png
  logo: assets/linkedin-logo.png
  language: 'pt'
  palette:
    primary: 'indigo'

nav:
  - Página Inicial: index.md
  - Planejamento do Projeto:
    - Cronograma de Atividades: cronograma.md
    - Análise dos aplicativos:  analise-app.md
    - Plano de Metodologias:  metodologias.md
    - Ferramentas utilizadas:   ferramentas.md