site_name: LinkedIn

theme: 
  name: material
  favicon: assets/linkedin-logo.png
  logo: assets/linkedin-logo.png
  language: 'pt'
  palette:
    primary: 'indigo'

nav:
  - Página Inicial: index.md
  - Planejamento do Projeto:
    - Cronograma de Atividades: ./planejamento/cronograma.md
    - Análise dos aplicativos:  ./planejamento/analise-app.md
    - Plano de Metodologias:    ./planejamento/metodologias.md
    - Ferramentas utilizadas:   ./planejamento/ferramentas.md
  - Pré-Rastreabilidade:
    - Rich Picture: ./preRastreabilidade/richPicture.md
  - Elicitação:
    - Personas: ./elicitacao/personas.md
    - Técnicas:
      - Brainstorm: ./elicitacao/brainstorm.md
      - Observação: ./elicitacao/observacao.md
      - Entrevistas: ./elicitacao/entrevistas.md
  - Atas e Reuniões: ./atas_e_reunioes/atas_reunioes.md
  - Apresentações: ./apresentacoes/apresentacoes.md
markdown_extensions:
- attr_list
